modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Recast"
logoFile="icon.png"

[[mods]]
modId="recast"
version="3.0"
displayName="Recast"
displayURL="https://curseforge.com/minecraft/mc-mods/recast"
authors="Rick South"
description='''Automatically re-casts the fishing rod for a player when they catch an item.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.recast]]
    modId="collective"
    mandatory=true
    versionRange="[6.13,)"
    ordering="NONE"
    side="BOTH"